name: Arduino CI (ESP32)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

    - name: Configure Arduino CLI for ESP32
      run: |
        arduino-cli config init
        arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

    - name: Install ESP32 Core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Compile Sketch for ESP32 DevKit
      run: arduino-cli compile --fqbn esp32:esp32:esp32doit-devkit-v1 slave-esp32/slave-esp32.ino

    - name: Verify Output
      run: echo "Build successful!"
